### ISSUE TITLE
RuntimeError: Characteristic value/descriptor operation failed: Invalid handle

### ISSUE THREAD

**Issue by r3-yamauchi** [OpenWonderLabs/python-host#19]
Ubuntu 18.04

`
$ sudo python3 switchbot_py3.py --device C7:96:B8:○○:○○:○○
Connected!
Traceback (most recent call last):
  File "switchbot_py3.py", line 109, in <module>
    main()
  File "switchbot_py3.py", line 104, in main
    driver.run_command('press')
  File "switchbot_py3.py", line 56, in run_command
    return self.req.write_by_handle(self.handle, self.commands[command])
RuntimeError: Characteristic value/descriptor operation failed: Invalid handle

$ sudo python3 switchbot_py3.py --device C7:96:B8:○○:○○:○○ Humiture
Connected!
Traceback (most recent call last):
  File "switchbot_py3.py", line 109, in <module>
    main()
  File "switchbot_py3.py", line 104, in main
    driver.run_command('press')
  File "switchbot_py3.py", line 56, in run_command
    return self.req.write_by_handle(self.handle, self.commands[command])
RuntimeError: Characteristic value/descriptor operation failed: Invalid handle
`

**Comment by SwitchBot-Wonderlabs** [comment]
switchbot_py3.py  does not support meter now, we will add it later.
Type `python3 switchbot_py3.py --help`  for usage tips.
