### ISSUE TITLE
Can't send commands - curtain

### ISSUE THREAD

**Issue by bakman2** [OpenWonderLabs/python-host#22]
```
sudo python3 switchbot_py3.py -s
Scanning for bluetooth low-energy devices
Discovering Switchbot services
 * Found Switchbot service on device F1:E2:0A:F3:6C:56 handle 13
Found 1 devices: ['F1:E2:0A:F3:6C:56']
Enter the number of the device you want to control:
	0	F1:E2:0A:F3:6C:56
0
Connected!
Traceback (most recent call last):
  File "switchbot_py3.py", line 178, in <module>
    main()
  File "switchbot_py3.py", line 173, in main
    driver.run_command(opts.command)
  File "switchbot_py3.py", line 122, in run_command
    return req.write_by_handle(self.handles[command], self.commands[command])
gattlib.GATTException: Characteristic value/descriptor operation failed: Invalid handle
```

```
sudo python3 switchbot_py3.py -d F1:E2:0A:F3:6C:56 -c open
Connected!
Command execution successful

sudo python3 switchbot_py3.py -d F1:E2:0A:F3:6C:56 -c close
Connected!
Command execution successful

```
Yet nothing happened, is there supposed to be error handling here ?

**Comment by leopoldwang** [comment]
I have created a pr to add support.

https://github.com/OpenWonderLabs/python-host/pull/24

**Comment by DavidCooperCheyney** [comment]
If you haven't calibrated the switchbot curtain, then it won't move with the commands provided.

**Comment by SwitchBot-Wonderlabs** [comment]
Try python2 - switchbot.py or python3 - switchbot_py2topy3.py.
switchbot_py3.py has some bugs.
